# Generated by Django 3.2.8 on 2023-07-04 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soulmates', '0003_auto_20230704_0622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='friends',
        ),
        migrations.AlterField(
            model_name='friend',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soulmates.member'),
        ),
    ]
