# Generated by Django 3.2.8 on 2023-07-04 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soulmates', '0004_auto_20230704_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='friends',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='soulmates.friend'),
        ),
    ]
