# Generated by Django 3.2.8 on 2023-07-04 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soulmates', '0005_member_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='friends',
        ),
        migrations.AddField(
            model_name='member',
            name='friends',
            field=models.ManyToManyField(to='soulmates.friend'),
        ),
    ]
