# Generated by Django 3.2.8 on 2023-07-08 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soulmates', '0008_member_my_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='my_friends',
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
