# Generated by Django 3.2.8 on 2023-07-14 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soulmates', '0016_auto_20230714_2109'),
    ]

    operations = [
        migrations.DeleteModel(
            name='messages',
        ),
    ]
