# Generated by Django 3.2.8 on 2023-07-16 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soulmates', '0019_public_room_chat_messages_is_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='public_room_chat_messages',
            old_name='is_admin',
            new_name='is_viewed',
        ),
    ]
