# Generated by Django 3.2.8 on 2023-07-23 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soulmates', '0028_auto_20230717_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='private_chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_friend', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_friend', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='private_chat_messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('private_chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_chat', to='soulmates.private_chat')),
            ],
        ),
    ]
