# Generated by Django 3.2.8 on 2023-07-26 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soulmates', '0031_rename_message_private_chat_messages_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='post_and_video_comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('date_of_post', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='replies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.CharField(max_length=255)),
                ('date_of_reply', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='post_photos_and_videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_or_video', models.ImageField(blank=True, default='C:\\Users\\mohamed irfaan\\OneDrive\\Pictures\\GHOST house.png', null=True, upload_to='posts/')),
                ('tags', models.CharField(max_length=255)),
                ('comments', models.ManyToManyField(to='soulmates.post_and_video_comments')),
            ],
        ),
        migrations.AddField(
            model_name='post_and_video_comments',
            name='reply',
            field=models.ManyToManyField(to='soulmates.replies'),
        ),
    ]
