# Generated by Django 3.2.8 on 2023-07-30 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soulmates', '0034_auto_20230730_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='private_chat_messages',
            name='message_sender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='message_sender', to='soulmates.member'),
            preserve_default=False,
        ),
    ]
