# Generated by Django 3.2.8 on 2023-08-01 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soulmates', '0037_public_chat_room_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_photos_and_videos',
            name='post_or_video',
            field=models.ImageField(blank=True, default='C:\\Code\\project\\matrimony\\media\\img\\default.jpg', null=True, upload_to='posts/'),
        ),
    ]
