# Generated by Django 3.2.8 on 2023-08-02 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soulmates', '0038_alter_post_photos_and_videos_post_or_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_and_video_comments',
            name='reply',
        ),
    ]
