# Generated by Django 3.2.8 on 2023-07-04 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soulmates', '0002_messages_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='from_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='messages',
            name='to_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
