# Generated by Django 3.2.8 on 2023-07-07 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soulmates', '0007_auto_20230706_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='my_friends',
            field=models.ManyToManyField(to='soulmates.friendlist'),
        ),
    ]
