# Generated by Django 3.2.8 on 2023-07-08 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soulmates', '0011_auto_20230708_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='my_friends',
        ),
    ]
