# Generated by Django 3.2.8 on 2023-07-08 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soulmates', '0012_remove_member_my_friends'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='name',
            new_name='username',
        ),
    ]
