# Generated by Django 3.2.8 on 2023-07-14 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soulmates', '0017_delete_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='public_chat_room',
            name='users',
            field=models.ManyToManyField(blank=True, help_text='users online', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='public_room_chat_messages',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room1', to='soulmates.public_chat_room'),
        ),
        migrations.AlterField(
            model_name='public_room_chat_messages',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1', to=settings.AUTH_USER_MODEL),
        ),
    ]
