# Generated by Django 3.2.8 on 2023-07-16 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soulmates', '0020_rename_is_admin_public_room_chat_messages_is_viewed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='public_room_chat_messages',
            name='is_viewed',
        ),
        migrations.RemoveField(
            model_name='public_room_chat_messages',
            name='content',
        ),
        migrations.AddField(
            model_name='public_room_chat_messages',
            name='content',
            field=models.ManyToManyField(blank=True, related_name='content', to='soulmates.Messages'),
        ),
    ]
