# Generated by Django 3.2.8 on 2023-07-16 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soulmates', '0022_auto_20230716_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='public_chat_room',
            name='content',
        ),
        migrations.AddField(
            model_name='public_room_chat_messages',
            name='content',
            field=models.ManyToManyField(blank=True, related_name='content', to='soulmates.Messages'),
        ),
    ]
