# Generated by Django 3.2.8 on 2023-07-17 05:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('soulmates', '0027_auto_20230717_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='public_room_chat_messages',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='public_room_chat_messages',
            name='content',
        ),
        migrations.AddField(
            model_name='public_room_chat_messages',
            name='content',
            field=models.TextField(default='message'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Messages',
        ),
    ]
