# Generated by Django 3.2.8 on 2023-07-30 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soulmates', '0033_auto_20230730_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='private_chat_messages',
            name='message_receiver',
        ),
        migrations.RemoveField(
            model_name='private_chat_messages',
            name='message_sender',
        ),
    ]
