# Generated by Django 3.2.8 on 2023-08-01 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soulmates', '0036_private_chat_messages_message_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='public_chat_room',
            name='profile_pic',
            field=models.ImageField(blank=True, default='C:\\Users\\mohamed irfaan\\OneDrive\\Pictures\\GHOST house.png', null=True, upload_to='images/'),
        ),
    ]
