# Generated by Django 3.2.8 on 2023-08-02 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soulmates', '0039_remove_post_and_video_comments_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_and_video_comments',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_sender', to='soulmates.member'),
            preserve_default=False,
        ),
    ]
